src/host.ts

If we have plugins that are ordered before typescript, e.g. `replace`,
the input to typescript should be the output of the previous plugin.
However, this doesn't happen, instead typescript transforms the original
file.
From my (possibly incorrect) analysis, this happens because of a cache
invalidation issue. If a module is processed by typescript before it is
transformed by the plugin, it seems the file is read directly from the
disk and inserted into the LanguageService `HostCache`. Later, when the
file is transformed by the plugin, there is a call to `setSnapshot` with
the "good" code (transformed by previous plugins), and then a call to
`getEmitOutput` which is expected to use the snapshot we had just set.
But this does *not* happen, instead we get the "bad" code from the
`HostCache`. …

Fix plugin chaining

---

README.md
dist/rollup-plugin-typescript2.cjs.js
dist/rollup-plugin-typescript2.es.js
src/index.ts
src/tscache.ts

This PR modifies the plugin to respect `declaration: true` in the `tsconfig.json` file.
When enabled, this plugin will collect the generated `*.d.ts` files from the typescript compilation, and write them out after the bundle has been written.
These files will be written out to the same folder as the destination bundle (possibly make this a configurable folder?)

Support declaration:true in tsconfig.json and emit declaration files

---

.gitignore
.vscode/settings.json
README.md
dist/get-options-overrides.d.ts
dist/host.d.ts
dist/index.d.ts
dist/parse-ts-config.d.ts
dist/print-diagnostics.d.ts
dist/rollup-plugin-typescript2.cjs.js
dist/rollup-plugin-typescript2.es.js
dist/tscache.d.ts
dist/tslib.d.ts
src/get-options-overrides.ts
src/host.ts
src/index.ts
src/ioptions.ts
src/irollup-options.ts
src/parse-ts-config.ts
src/partial.ts
src/print-diagnostics.ts
src/rollingcache.ts
src/rollupcontext.ts
src/tscache.ts
src/tslib.ts

This PR makes the generated declaration files share the same directory root as the bundle generated by rollup.
Before, the declaration file would respect the *outDir* property of a `tsconfig.json` file and write declaration files to that directory.
This has two significant issues:
- If the *outDir* isn't the same as the generated .js files, Typescript doesn't know where to go look for the typings without manual work on the user's end.
- If more than one transform target is used in a rollup bundle (such as es2015 and umd), the declaration files will only be generated once and live outside the root of the generated folders
A previous PR has been submitted which unfortunately did not resolve this issue and, additionally, didn't handle scenarios where multiple compile targets are defined in …

Make declarations share directory root with generated bundle(s)

---

package.json

After I upgrade to v0.6.0, it show me an error:
```
Error: Cannot find module 'rollup-pluginutils'
```
So I move `rollup-pluginutils` to _dependencies_.
BTW I add `typescript` and `rollup` to _peerDependencies_, so if user doesn't install it(or version incompatible), NPM will show a tip in console.

improve dependencies

---

dist/ioptions.d.ts
dist/rollup-plugin-typescript2.cjs.js
dist/rollup-plugin-typescript2.es.js
package.json
rollup.config.js
src/index.ts
src/ioptions.ts

Fixes #37 
The implementation is pretty straightforward: if a `rootDirs` tsconfig option is set, the filter is created by permuting and flat-mapping `rootDirs` and `include`.
So the default `include: ["*.ts+(|x)", "**/*.ts+(|x)"],`, along with `rootDirs: ["./src","../../shared/lib/src"]`, would create a filter for:
```
./src/*.ts+(|x)
./src/**/*.ts+(|x)
../../shared/lib/src/*.ts+(|x)
../../shared/lib/src/**/*.ts+(|x)
```
A user could also specify their own `include` as part of the plugin's configuration, and it should be applied correctly.
This works for my use case, but I don't have a very robust way of testing other project configurations, so you might want to test this more before releasing.
Cheers!

feat: Support rootDirs compiler option

---

src/get-options-overrides.ts

Currently if you have ```noEmit: true``` in your tsconfig.json file then running rollup with this plugin just errors without telling you why it failed. Its quite common to have this option set I think to prevent lots of files being created when running tsc. It may also be worth improving the error message when nothing is emitted by the typescript compiler.

override noEmit option to false when set

---

src/parse-tsconfig.ts

Now prints fancy messages like this one:
```
rpt2: config error TS18003 No inputs were found in config file '<path>/tsconfig.json'. Specified 'include' paths were '["src/"]' and 'exclude' paths were '["node_modules/"]'.
```
Fixes #106

Add tsconfig error reporting

---

src/index.ts

make the `typescript` not a strong required dependence. allow customize typescript implements like:
```js
// rollup.config.js
// ...
plugins: [
ts2({
typescript: require('@allex/typescript'),
tsconfig: resolve('tsconfig.json'),
check: false
})
// ...
]
```

Optional dependency of typescript.

---

src/print-diagnostics.ts

MSBuild and many other tools / IDEs will correctly parse the message if ":" is added right after the error code.
See https://blogs.msdn.microsoft.com/msbuild/2006/11/02/msbuild-visual-studio-aware-error-messages-and-message-formats/ for reference.

Update diagnostic message according to standard tool parsing.

---

README.md

An extension name should start with a `.` in the `extensions` option of babel config. (As described here: https://babeljs.io/docs/en/babel-core#default-extensions)

Fix extension name in babel config

---

.gitignore
README.md
package-lock.json
package.json
src/index.ts

Fixes #133
The default `cacheRoot` is now `./node_modules/.cache` (which is the de facto standard cache location of npm packages), making it easier to use the package without needing to ignore any additional directories. The `cacheRoot` can still be changed if the user needs the original location for some reason.
I removed the cache from our own gitignore, but the version saved to `dist` still uses the old `cacheRoot`. After this is merged, it should be updated with `npm run build` and then `.rpt2_cache` can be deleted before committing. If you'd prefer, I could do it in this PR, but I wasn't sure what the process for updating `dist` was.

Move cache directory to node_modules

---

src/index.ts
src/tslib.ts

Rollup has `preserveModules` option which is used to skip flat bundling and writing instead to disk a directory structure resembling the input one. This plugin makes tslib a "virtual" module by default - this means that it virtually creates an input file for Rollup to consume, but obviously it's not part of the input directory structure. To deal with it in combination with `preserveModules` Rollup creates a `_virtual` output directory and put such modules in it. As filename of such a virtual module it uses "as is" the given identifier - in this case `\0tslib`. Problem is that it doesn't add any extension to it and this trips other tools if you don't include the extension in the virtual identifier - i.e. webpack and it's resolving algorithm.

Add .js extension to virtual tslib

---

package.json

With Rollup 1.25.1, the build (including build-self, multiple times) works again even with patch 551a14e773141cd993bb9d1ffd349c92481edf11 .
However, since the peerDependency still says `">=0.68.0"`, users might still run into issues when trying to run the plugin with an older Rollup that still has the bug. Should we also set the peer dep to the current version? Or consider Rollup bugs outside of the responsibility of the plugin? Or block on that?

Upgrade rollup

---

README.md
src/get-options-overrides.ts
src/host.ts
src/index.ts
src/ioptions.ts
src/parse-tsconfig.ts

Then we can run rollup+rollup-plugin-typescript2 with lerna projects.
ref: 
* https://github.com/umijs/father/issues/158
* https://github.com/umijs/father/issues/97

feat: support options.cwd

---

package-lock.json
package.json

- object-hash v2.0.2 adds/fixes support for async functions
- object-hash v2 has no breaking changes, just drops testing of
Node < 6
- Node 5 was EOL April 2018, and on top of that Node 6
was EOL April 2019, and Node 8 was EOL December 2019, so this is
still more tested support than is necessary
- objectHashIgnoreUnknownHack isn't useful for its original purpose to
workaround this, but is still useful for other types of
objects/syntaxes that object-hash may not handle yet
(e.g. async generator functions), so leave the hack in
- might be good to add a warning though? so that those who used this
option for async/await can upgrade and remove it (and have a
stable cache again)
<hr>
**Note**: I added an initial commit in here that auto-updates the `package-lock.json` as it hadn't been updated …

(fix): upgrade object-hash to support async/await syntax

---

README.md

- so remove that reference to objectHashIgnoreUnknownHack
- also be more specific about what cases objectHashIgnoreUnknownHack
might be needed for
- asyncgeneratorfunctions are still one off the top of my head, but
there are certainly others it just won't know about, including
future syntaxes
<hr>
Follow-up to #203 . Sorry probably should've changed the docs in the same go as that fix, but was moving too fast and didn't quite think about it until after. This I found while incidentally reading the docs for something else.

(docs): async plugins are now supported out-of-the-box

---

src/index.ts

- more importantly, using Plugin ensures that the types are accurate
Follow-up to #221 regarding the interface.
I removed the manual types here but I suppose you could also leave them in and just add the interface. Let me know if you want to do that instead and I'll update this

(refactor): use Rollup's Plugin interface instead of manual types

---

src/rollingcache.ts

Today I stumbled upon an error where it would fail when the cache folder was not present
```(typescript) Error: ENOENT: no such file or directory, rename 'REDACTED\node_modules\.cache\rollup-plugin-typescript2/rpt2_759e2fd8d3f20c1a0805faf5404af6bea36632fd/code/cache_' -> 'REDACTED\node_modules\.cache\rollup-plugin-typescript2/rpt2_759e2fd8d3f20c1a0805faf5404af6bea36632fd/code/cache'```
This PR fixes it by checking its existence before trying to rename it

stop roll() from failing if the new cache folder is not created

---

README.md
src/get-options-overrides.ts
src/index.ts

- change declarationDir default to be Rollup's output destination
instead of cwd
- previously, it was set to cwd if useTsconfigDeclarationDir wasn't
true, however, declarations aren't output to cwd, but to Rollup's
output destination, so this was incorrect
- also change the one line in the docs that says it'll be
`process.cwd()`; every other reference says it'll be the output dest
Fixes #204 and downstream https://github.com/jaredpalmer/tsdx/issues/479 . Better solution to downstream https://github.com/jaredpalmer/tsdx/issues/488
Couldn't change `get-options-overrides` because the `options` hook only gets `InputOptions`; it's not till `generateBundle` that we get access to `OutputOptions`.
RE: multiple output dirs: Rollup will call `generateBundle` for each output as far as I understand. …

(fix): declaration maps should have correct sources

---

.github/issue_template.md

- replace the version list with a copy+paste this envinfo command,
copy back the output
- uses a modified, shortened variant of something being used
successfully downstream in TSDX: https://github.com/formium/tsdx/commit/349f299976141c7d4f0a71b22d998319e54a3c9d
- this should make reporting versions zero-effort and thereby
significantly decrease non-reporting by making the hard thing easy
- personally have experienced issues that didn't report but version
was very relevant to the issue
- also some folks report "latest" or used carets, which lack posterity
or are confusing
Modified, shortened variant of https://github.com/formium/tsdx/pull/820
It looks like this when running in TSDX for example:
```bash
$ npx envinfo --npmPackages typescript,rollup,rollup-plugin-typescript2
npx: installed 1 …
```

github: use envinfo for getting versions in issue reports

---

.github/issue_template.md

- long logs of output or long configs are hard on the eyes and make it
difficult to read through issues as they just take up so much space
- so it would be better, in my opinion, to hide them by default with
spoiler tags, which can be opened up when further investigation is
warranted
- some issue authors have already used this pattern, this just brings
it to the template itself so everyone (hopefully) starts using it
Can see examples of spoiler tag usage in #97, #148, and my own https://github.com/ezolenko/rollup-plugin-typescript2/issues/212#issuecomment-594248522
Can see examples of very long output logs and/or configs in #72, #85, #87, #194,  #213, #217
Been meaning to write this PR for quite a while actually, finally got to it 😅

github: add spoiler tags to issue template

---

src/get-options-overrides.ts

When compilerOptions.rootDir is specified, it is used instead of process.cwd() to filter files. 
Possible fix for #237

fix: use compilerOptions.rootDir to filter files

---

src/index.ts

On Windows the normalized paths in resolveId end up in POSIX format.
This cause rollup to treat the returned path as a new piece of content.
This in turn results in duplicate output for references across entry points.
Fixed by normalizing the path to use host OS separators before returning.
See https://github.com/antross/rollup-plugin-typescript2-repro for a repro project.

Fix duplicate output with multiple entry points

---

README.md
package.json

Version 2 of yarn uses Plug'n'Play, which means that the user's installed `typescript` (which is used because `typescript` is set as a peer dependency for this plugin) won't have access to the `tslib` marked as a dependency for this plugin.
https://github.com/yarnpkg/berry/issues/2140
People using version 2 of yarn have to manually install `tslib` in `devDependencies`. This PR makes it so that everyone would need to manually install `tslib` as well, which is what should actually happen.

Add tslib to installation instructions

---

src/host.ts

At the moment I'm debugging a weird difference in behavior between `tsc` and `tsdx` (where the latter is using this plugin) and being able to look through the output of `traceResolution` is super helpful for me - but I had to patch this plugin locally to make it work. It would be great if this option would just be respected by the plugin.

Add `trace` method to the `LanguageServiceHost` to enable usage with `traceResolution`

---

.github/issue_template.md

Improve formatting of the issue template with code blocks and fixing some duplication
- I originally added the spoilers in #244 and while they work (and I would say improve readability a good bit), there's also some issues with them
- I've used them a ton more now so know how to workaround most of the issues with them now
- fix: use HTML `code` tag inside of `summary` tag, can't use backticks
- was mixing MD and HTML before, and this doesn't always work and didn't work on GitHub, they just had visible backticks before
- fix: don't duplicate the file name in the heading, just make the `summary` have a heading inside it instead
- use an `h4` same as the `####` that it was before
- feat: add syntax highlighting by adding code blocks for each code snippet
- `js` for `rollup.config.js`, …

fix(github): improve formatting of issue template spoilers

---

README.md

Consistently use the same style when referencing issues in this repo and in other repos -- follow how GitHub does it.
- fix: missing `#` in `outDir` reference ("83")
- use `org/repo#num` consistently
- this is how GitHub displays references to other repos in comments as well, so consistent with the rest of GH too
- previously was either `Microsoft/TypeScript/issues/num` or `rollup/issues/num` inconsistently
- links haven't changed, just the text of the them
Unrelated:
- auto-trim some whitespace-only lines
- my editor does this automatically, and most of the README has trimmed whitespace anyway, so this keeps it consistent
See this PR's rendered [README.md](https://github.com/ezolenko/rollup-plugin-typescript2/blob/8346a426ea776b3186e18bd117ee26f13044e66f/README.md)

docs: standardize how issues are referenced

---

package-lock.json
package.json

Remove `@types/colors` from devDeps as it's no longer necessary
- it had a deprecation warning on install stating that types were built-in now
- confirmed that my editor picks up the types fine without and that builds still work
- auto-alphabetize deps
- update `package-lock.json` version to match `package.json` version
- NPM did both of these automatically when I ran `npm install`

deps: remove unneeded `@types/colors` package

---

README.md

Be more clear about what the TS option does and what its default is -- the current peerDependency installed
- "latest 2.x" is no longer accurate and quite outdated (we're on `4.x` now), so just say it's the peerDep instead
- @rollup/plugin-typescript calls the default a peerDep too: https://github.com/rollup/plugins/tree/master/packages/typescript#typescript
- be more specific that you can pass in a different version or fork of TS (like `ttypescript`) through this option
- follow-up to 8ec49c78f523687deaf6816bc2ea320f16e325c7 and #252
Unrelated:
- auto-trim some whitespace-only lines
- my editor does this automatically, and most of the README has trimmed whitespace anyway, so this keeps it consistent

docs: clarify the TS option's defaults

---

dist/normalize.d.ts
dist/normalize.d.ts.map
src/host.ts
src/index.ts
src/normalize.ts

Replaces `normalize.ts` with `normalizePath` from `@rollup/pluginutils`
- this was introduced in [`v4.1.0`](https://github.com/rollup/plugins/blob/master/packages/pluginutils/CHANGELOG.md#v410) of `@rollup/pluginutils` in https://github.com/rollup/plugins/pull/550
- we're currently on `^4.1.2` for reference
- this is the same as the code in `normalize.ts` but it uses constants from Node and is used by multiple Rollup plugins, so just helps with standardization
- also less code and types to ship in the bundle!
- removed the dist files for `normalize` as well, but didn't do a build in this commit as those are usually done in separate commits

deps: use `normalizePath` from `@rollup/pluginutils`

---

CONTRIBUTING.md
README.md

Split off CONTRIBUTING.md from README.md and improve a few pieces of it
Wrote as two commits so that it's easier to review the diff. First is pure split, second is changes.
- condenses the README a bit and uses the standard CONTRIBUTING.md file
- it's a file I often look for when filing an issue or creating a PR
- leaves the section still in the README so that users (esp. on NPM) will know to go there if they're not aware of that convention
- GitHub also now tells users to read the CONTRIBUTING.md of a repo when filing issues or creating PRs, so hopefully this helps point more users in the right direction as well
- slightly change reference to GH Issue Tracker
- use oxford commas everywhere for clarity
- missing "the" in a few places
- more minor grammatical fixes (missing space, …

docs: split off a CONTRIBUTING.md and improve formatting, grammar, links

---

dist/partial.d.ts
dist/partial.d.ts.map
src/index.ts
src/partial.ts

`Partial` is built into TS, so clean up & remove `partial.ts`
- Built-in at least as of TS 2.1: https://www.typescriptlang.org/docs/handbook/utility-types.html#partialtype
- we have a peerDep on TS >=2.4, so should definitely be compatible
- and TS is on ~4.6 at this point, so that's _really_ old
- remove the file and the declarations and declaration maps
- don't rebuild as that's usually done as a separate commit

clean: remove `partial.ts` as this is built into TS

---

.github/workflows/nodejs.yml

Optimize CI by using `npm ci` and caching `npm` installs
- `npm ci` is installation for, well, CI, and is a good bit faster
- c.f. https://docs.npmjs.com/cli/v8/commands/npm-ci
- cache `npm` installation with `setup-node` for speedier installs
- upgrade `setup-node` as this was released in [v2.2.0](https://github.com/actions/setup-node/releases/tag/v2.2.0)

optim(ci): use `npm ci` for install and cache `npm`

---

__tests__/tslib.spec.ts
package-lock.json
package.json
src/tslib.ts

Resolves #286 in a simpler way by upgrading `tslib` instead of introducing any new deps
- Replaces #289 / #290 
Implements the approach I proposed in https://github.com/ezolenko/rollup-plugin-typescript2/issues/286#issuecomment-1120270016 
- `tslib` `2.4.0` is forward and backward-compatible with older and newer Node exports mechanisms, so the Node 17 error should no longer be present
- see its [`package.json`](https://github.com/microsoft/tslib/blob/a7129c7bd500ce378ec19234247f3d0b1635e89d/package.json#L35) after https://github.com/microsoft/tslib/pull/135
- it has the older `./` and the newer `./*` in its package exports, which should allow for `package.json` to be read in both older and newer implementations
- this allows us to remove the extra dep on `@yarn-tool/resolve-package` as …

deps: upgrade `tslib` to `^2.4.0`, remove `@yarn-tool/resolve-package`

---

.github/workflows/nodejs.yml

Run `npm run lint` in CI
- rename the job a bit to match, and shrink the name a bit for conciseness as it didn't always fit on screen in the list of checks
- this could be done in a different job as it's not necessarily required for linting to run through the entire matrix, but this is simpler for now as we don't have a further need for separate jobs
- and no need to re-run install etc, and the tests are fast anyway currently, so no perf need there either
1. Still need to upgrade to `@typescript-eslint` -- this might be good for a community contribution?
1. Could add a formatter like `prettier` as well instead of relying on `editorconfig` etc (a lot of style things are currently missed by `lint`; something I notice in particular as I typically use single quotes and no semi-colons and need …

ci: add a lint check to ensure all PRs pass lint too

---

src/get-options-overrides.ts
src/host.ts
src/index.ts
src/parse-tsconfig.ts
src/print-diagnostics.ts
src/tscache.ts

Replace most (not all) `lodash` methods with native methods
- `_.endsWith` -> String.endsWith
- `_.concat` -> Array.concat
- `_.each` -> Array.forEach
- `_.filter` -> Array.filter
- `_.map` -> Array.map
- `_.some` -> Array.some
- `_.has` -> `key in Object`
- `_.defaults` -> Object.assign
- `_.get` -> `?.` and `??` (optional chaining and nullish coalescing)
- refactor: replace fairly complicated `expandIncludeWithDirs` func to just use a few simple `forEach`s
- not as FP anymore, more imperative, but much simpler to read IMO
- refactor: add a `getDiagnostics` helper to DRY up some code
- also aids readability IMO
- a few places are still using lodash, but this paves the way toward removing it or replacing it with much smaller individual deps
- `_.compact` still used because Array.filter …

refactor: prefer native methods to lodash where possible

---

__tests__/get-options-overrides.spec.ts
src/get-options-overrides.ts

`get-options-overrides.ts` had some paths that were not normalized, resulting in mixed separators on Windows in certain cases.
- Fixes https://github.com/ezolenko/rollup-plugin-typescript2/pull/321#discussion_r869710856
- Fixes https://github.com/ezolenko/rollup-plugin-typescript2/pull/329#discussion_r873108879
- Also follow-up to https://github.com/ezolenko/rollup-plugin-typescript2/pull/329#issuecomment-1138876847
- the `outDir` was not normalized after the `/placeholder` part was added to `cacheRoot`
- `cacheRoot` could have `\` directory separators on it on Windows, which caused some tests to fail on Windows before
- tests have been normalized now too
- `expandIncludeWithDirs` used `path.join` without normalizing after
- `path.join` uses the OS's native separators (`posix.join` would …

fix: normalize paths in `get-options-overrides`

---

__tests__/host.spec.ts
src/host.ts

Implement `realpath` in `host.ts` to properly resolve symlinks, i.e. for monorepos
While the code for this is tiny, this is a pretty _huge_ bugfix given the number of users that have run into this here and downstream (in `microbundle`, TSDX, etc) -- glad to finally fix such a common error!
- tested this in a `pnpm` repo with symlinked deps and it worked there, so I believe this fixes all `pnpm` issues
- it may also fix some Lerna issues if they were due to symlinks, but I didn't check those
- not sure about others, e.g. Rush, Yarn workspaces, Yarn PnP
- I figured out this was needed by staring at the TS source code and then I found this [line](https://github.com/microsoft/TypeScript/blob/67673f324dd5f9398bb53fd16bf75efd155c32e7/src/compiler/moduleNameResolver.ts#L1412) 
- it expects …

fix: add `realpath` to host to properly resolve monorepos

---

src/index.ts

For the `rollup-plugin-vue` integration, output declarations as `name.d.ts` instead of `name.vue.d.ts`
- Fixes #224 , follow-up to https://github.com/ezolenko/rollup-plugin-typescript2/issues/224#issuecomment-642790321
- `.vue.d.ts` was recommended by the `rollup-plugin-vue` maintainers in https://github.com/ezolenko/rollup-plugin-typescript2/issues/97#issuecomment-405607066 back when this code was originally written, but apparently it causes problems with some imports according to #224
- plain `.d.ts` seems to work fine according to users in that issue
- and plain is the standard in TS too I believe?

fix: use `.d.ts` instead of `.vue.d.ts` for Vue declarations 

---

src/index.ts
src/tscache.ts

Small refactor to invert some conditionals/`if` statements for better readability
- handful of refactors I'm making as I'm now very familiar with the codebase to make it easier to work with and more approachable to new contributors as well
- a few `if (cond) { big block } return` could be inverted to `if (!cond) return` then the block un-indented instead
- generally speaking, this makes it a lot more readable (less indentation, etc) and follows the existing code style in much of the codebase, where it's a few quick one-line ifs and then just the rest of the code
- shorten the resolvedFileName conditional by using optional chaining
- prefer the simpler `x?.y` over the older `x && x.y` syntax
- add a `resolved` variable for less repetition of the whole statement
- add a comment to the …

refactor: invert some conditionals for better readability

---

src/index.ts

Skip transforming declarationMap `sources` when there is no output, i.e. in the case of using rpt2 as a [`configPlugin`](https://rollupjs.org/guide/en/#--configplugin-plugin)
- Fixes #310 
- when using rpt2 as a `configPlugin`, there is no Rollup `output`, so it will be `undefined`
- when `declarationMap: true` in `tsconfig`, this block of code is called as a workaround due to the `placeholder` dir we must use for output -- but, in this case, it errors out, since the `declarationDir` is `undefined`
- `path.relative` needs a `string` as a arg, not `undefined`
- so skip this transformation entirely when there's no `output`, as it doesn't need to be done in that case anyway
- this transformation code happens to have been written by me 2 years ago too in #221, so I had fixed one bug with that …

fix: don't attempt to change declarationMap `sources` when no output

---

README.md
__tests__/get-options-overrides.spec.ts
src/get-options-overrides.ts

Force `noEmitOnError: false` for the same reason we force `noEmit: false`
- Fixes #254
- `noEmitOnError: true` acts like `noEmit: true` when there is an error
- this is problematic because it will then cause _all_ files to have [`emitSkipped`](https://github.com/ezolenko/rollup-plugin-typescript2/blob/e8240ae505a6c4d0b7faa997e3c2d75d293c594a/src/index.ts#L205) set to `true`, which this plugin interprets as a fatal error
- meaning it will treat the first file it finds as having a fatal error and then abort, but possibly without outputting any diagnostics what-so-ever as the file with the error in it may not yet have run through the `transform` hook
- i.e. an initial file that imports an erroring file at some point in its import chain will cause rpt2 to abort, even if that initial file …

fix: force `noEmitOnError: false`

---

src/index.ts

Tiny one-line optimization: `getScriptSnapshot` was called when we already have the snapshot
- the snapshot is set above, so no need to get it
- also the snapshot from above is used below already, so this doesn't seem to be intentional
- it originates from https://github.com/ezolenko/rollup-plugin-typescript2/commit/2d330640316894752bae5ae64d94bc90652e4564#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80R197 which similarly doesn't seem intentional

optim: don't `getScriptSnapshot` when we already have the snapshot

---

src/index.ts

Set `noErrors = false` when checking `compilerOptions` errors as well
- previously, while errors would be printed, the flag for `noErrors` was not set to `false`, and so there would be no yellow warning about errors
- this is mostly just fixing asymmetric UX, but personally, I actually have missed this error before myself, so maybe this will help alleviate that kind of situation

fix: set `noErrors = false` when there are `compilerOptions` errors

---

src/index.ts

Remove an old, redundant check against `allImportedFiles` that is actually dead code
- this checks if any of the files in `parsedConfig.fileNames` are _not_ in `allImportedFiles`, but all the files in `parsedConfig.fileNames` are explicitly added in the `options` hook on [line 98](https://github.com/ezolenko/rollup-plugin-typescript2/blob/44116044750b01c3b0d612e36f453cc8e64f79b4/src/index.ts#L98)
- so this is redundant / dead code; the check will never be true
- this can be considered a remnant of an old bug as an old commit fixed a bug with `allImportedFiles` after it was released: #176

clean: remove redundant `allImportedFiles` check in `_onwrite`

---

src/index.ts

Only output declarations for files that pass the `filter` check so there isn't a mismatch between JS being `exclude`d, but DTS declarations still being output.
- Fixes #225 
- Fixes #280
- Fixes the pattern of bugs causing confusion around plugin `include` / `exclude` vs. `tsconfig` `include` / `exclude` that I mentioned in https://github.com/ezolenko/rollup-plugin-typescript2/pull/311#issuecomment-1145551324
- these should run through the same `filter` as runs in `transform` etc
- prior to this, the plugin `exclude` would filter files in `transform`, meaning no JS would be output for them, but would still output declarations for these very same files that no JS was produced for
- (this would only happen if one were using an `include` glob or something that made the file appear twice, …

fix: `filter` "missed" declarations as well

---

src/get-options-overrides.ts

Invert an `if` conditional in `get-options-overrides` for readability
- Basically, a follow-up to #335 
- my previous commit was mostly focused on `index.ts`, this one is for `get-options-overrides` -- in general, I'm just trying to old code more readable as I come across and then realize that the code can be re-written better, or, in this case, a conditional inverted
This one's not a big improvement either way and not a complete inversion (it's just an early return of the same final return), so also feel free to reject this. I don't feel strongly about it, but figured I might as well rewrite it to follow the same kind of style found elsewhere

refactor: invert another if for readabilty -- in `get-options-overrides`

---

__tests__/host.spec.ts
src/diagnostics-format-host.ts
src/host.ts

Simplify host files with `public func = tsModules.sys.func` where possible
- Technically a follow-up to #321 as I was trying to get this to work at the same time, but ran into some testing issues (see below) and then backlogged it for a while as such
- no need to duplicate types this way, which can and _have_ changed over time (some of the function args have more parameters etc now actually) -- it's always the same typings this way
- also reorganize `host.ts` to have similar categories of functions near each other, instead of a mix of functions wherever
- similar to how I organized the tests for `host.ts` as well
- shrink the code a bit this way too
- add a comment about `getDefaultLibFileName`'s confusing naming pointing to the TS issues about how this is an old mistake but changing it …

refactor: simplify hosts to directly assign `tsModule.sys` where possible

---

.github/issue_template.md
CONTRIBUTING.md

Add 3 _very common_ troubleshooting steps to the issue template to help both users and maintainers/contributors
- Hopefully addresses the _most common_ pattern that I noticed in the issues per https://github.com/ezolenko/rollup-plugin-typescript2/pull/311#issuecomment-1115491161
- these steps should help in 2 ways:
1. hopefully avoid common misconfigurations from being repeatedly opened as bug reports
- [some](https://github.com/ezolenko/rollup-plugin-typescript2/issues?q=is%3Aissue+label%3A%22problem%3A+plugin+order%22+) of these have labels on them now to get a sense of how often they pop up
2. help contributors and maintainers diagnose issues quicker as well as figure out if an issue is indeed a bug
- the diagnosis questions are really common things we ask in an issue already, so think …

github: add troubleshooting steps to the issue template

---

CONTRIBUTING.md

Add a sizeable "Learning the codebase" section to the contributing docs to help new contributors!
- thought that as it's somewhat? fresh in my head (pending if you consider years of sporadic contributions), it would be really good to document for new contributors who don't know where to start
- other than being good practice, thought this could be useful for a number of reasons:
1. helpful resources like the [TSConfig Reference](https://www.typescriptlang.org/tsconfig), the [TS Compiler Wiki](https://github.com/microsoft/TypeScript/wiki/Using-the-Compiler-API), and the Rollup [Plugin docs](https://rollupjs.org/guide/en/#plugins-overview), that I read through with some frequency
- (and I [contribute lots](https://github.com/microsoft/TypeScript-Website/pulls?q=is%3Apr+author%3Aagilgur5) to …

docs: add a section on "Learning the codebase" to `CONTRIBUTING.md`

---

.github/issue_template.md

Add global TS version, OS, Node, and package manager details to `envinfo` command in the issue template
- add global version of TS as well
- with some frequency, people report not having the same issue with `tsc`, and in some cases, that's because they're using their globally installed version of `tsc`, which is at a different version than their project's `tsc` (e.g. #223)
- this will help guard against that
- add OS and CPU details
- OS bc non-POSIX [path separator issues](https://github.com/ezolenko/rollup-plugin-typescript2/labels/topic%3A%20OS%20separators) with Windows are somewhat common
- CPU in case certain architecture may have an impact, e.g. new Apple ARM Silicon in Mac M1/M2 etc
- it really shouldn't as this is mostly a high-level library, but some of the lower level …

github: add more environment details to `envinfo`

---

.github/issue_template.md

Add a repro env to the issue template to get people to make more repros!
- Should hopefully help solve one of the patterns of lack of repros I noticed in https://github.com/ezolenko/rollup-plugin-typescript2/pull/311#issuecomment-1115491161
- this should help make reproductions easier as it gives a quick starting point requiring no boilerplate and is easily accessible from a browser too
- decided to go with StackBlitz over CodeSandbox and repl.it as it's [WebContainer tech](https://blog.stackblitz.com/posts/introducing-webcontainers/) allows for running Node projects entirely _inside_ the browser (via WebAssembly)
- meaning that unlike CodeSandbox and repl.it, their platform doesn't need to spin up and connect to a container on the backend
- so it's much more efficient, performant, and …

github: add a reproduction environment to the issue template

---

src/tscache.ts

- Modify `isDirty` comment to use typedoc
- Add a comment to specify that a condition is an invariant in `init`
- use typedoc for `isDirty` comment so that it actually appears in IDEs etc
- and use [`@returns`](https://typedoc.org/guides/doccomments/#%40return(s)) typedoc annotation for better specification
- modify the comment a little for better grammar: 3 "or"s and no commas -> 1 "or" and commas
- use more accurate terminology: "global types" -> "ambient types"
- that's also more consistent in this codebase itself, where there's a legit function named `checkAmbientTypes`
- in `init`, specify that the `RollingCache` error should never actually happen
- I was a bit confused by when this would happen, then checked the constructor, and the answer is basically never: it's an invariant / …

docs(cache): add/change some comments for clarity

---

src/tscache.ts

Rename `makeName` -> `createHash` and `name` -> `hash` in `tscache.ts` code for clarity
- I've actually been confused multiple times as to what `makeName` does when I read through the cache
- I re-read the code and then am like "oh it's the hash"...
- so thought renaming it to `createHash` would make things **a lot** clearer
- `Name` -> `Hash`
- `make` -> `create` because that's the more common terminology in programming
- also rename variables that reference `makeName`'s return from `name` to `hash`
- for the same reason around clarity -- this way it's quicker to interpret whenever you see it too
- not to mention, `name` can be confusing since we also have `id`, which is a path that is very similar to a name too
- and lots of `fileName`s too
- so good to disambiguate/differentiate a bit …

refactor(cache): `makeName` -> `createHash` for clarity

---

src/tscache.ts

Simplify a conditional in `tscache.ts` by using optional chaining
- as I've done in other places (e.g. #335), simplify a condition by using optional chaining syntax (over the previously necessary syntax with `&&` etc)
- also add a new line to the first `.map` here
- for style consistency and because this is a super long line
- this wasn't possible before the lodash refactor (#328) because it was all one big single statement in the chain

refactor(cache): simplify condition w/ optional chaining

---

src/tscache.ts

Add a `/** @returns */` typedoc comment to `createHash` to explicitly mention that it has to be FS-safe
- Follow-up to https://github.com/ezolenko/rollup-plugin-typescript2/pull/355#issuecomment-1155333976
- per follow-up comments, this has to be FS-safe, so I thought it would be good to explicitly mention that somewhere

docs(cache): add a typedoc `@returns` to `createHash`

---

src/index.ts
src/tscache.ts

Simplify `TsCache`'s `clean` method to be more straightforward, less nesting, etc
- `cache().clean()` is only called during instantiation in `options`, so we can instead just call it inside of the constructor
- there is no need to call `this.init()` in `clean` as it's only used in the constructor anyway, which already calls `this.init()`
- and if `noCache` is `true`, `init` is basically a no-op too
- so technically we don't need to call `init` _at all_ if `noCache`, but that's a larger refactor that I'm splitting into a separate commit/PR
<br />
- now that `clean` is just one conditional, we can invert it and return early instead
- it's also not necessary and less efficient to call `emptyDir` before `remove`; `remove` will unlink all the contents anyway
- docs …

refactor(cache): simplify `clean` method

---

src/index.ts

Split out a common `typecheckFile` function used in 3+ places to DRY up more code
- this is used in 3 places and going to be more for the code I'm adding to fix type-only imports in #345 (and probably more type-only PRs in the future)
- so DRY it up and standardize the functionality too
- some places had `noErrors = false` in one place while others had it in another
- same for `printDiagnostics`
- but the ordering actually doesn't matter, so just keep it consistent and the same
- and then can split a common function that does both out
- technically, now `getDiagnostics` (from #328) is now _only_ used in `typecheckFile`, so I could combine the two together, but I'm refactoring that one up a little
- but this a good, small example of how refactoring one part of a codebase can make it easier …

refactor: split out a common `typecheckFile` func

---

src/index.ts

Tiny one-liner change to use optional chaining
- following other optional chaining simplifications like #356, #335
Is `sourceMapCallback` actually used by anyone? It's not listed in the docs so I didn't know it was a thing until I saw it in the code

refactor: use optional chaining for `sourceMapCallback`

---

README.md
src/index.ts

Support `emitDeclarationOnly` by, well, only emitting declarations and type-checking, and otherwise passing to the next plugin to transform TS
- Fixes #268
- when `emitDeclarationOnly` is set, only perform type-checking and emit declarations, don't transform TS
- `result.code` actually doesn't exist when `emitDeclarationOnly` is set anyway
- this caused a confusing situation for users who were trying to use Babel (with Babel plugins) on TS and only use rpt2 for declarations
- instead of getting any JS code, they would just get empty chunks, bc `result.code` is `undefined`
- that's kind of buggy, it should probably either be forced to `false` or do what we're doing now, which is likely more intuitive / intended
- note that other Rollup TS plugins just force it to `false`, but I'm not sure …

feat: support `emitDeclarationOnly`

---

README.md
package-lock.json
package.json
src/index.ts

Formally deprecate `rollupCommonJSResolveHack` as it's been obsolete since [0.30.0](https://github.com/ezolenko/rollup-plugin-typescript2/releases/0.30.0)
- this has had no effect since #251
- that changed the code to always return OS native paths via the NodeJS Path API
- so setting `rollupCommonJSResolveHack` would make no difference either `true` or `false`
- effectively, it's as if it's always `true` now
- formally state now that this is deprecated in the docs
- as well as when that occurred and what it means
- also add a warning in `options` similar to the existing one for `objectHashIgnoreUnknownHack` (from cd76b42f5509b8ab7b1564373ed2b2ce0d5c7bdd, which was added to my first major contribution back in #203 🙂 )
- remove the `resolve` dependency as well
- it turns out something in …

docs/clean: formally deprecate `rollupCommonJSResolveHack`

---

src/tscache.ts

Decent size simplification in `tscache` so that `getDiagnostics` and `getCompiled` call a common `getCached` function, which is just a tiny refactor of the code that `getDiagnostics` already had.
- basically, refactor the `getDiagnostics` a tiny bit to also handle what the `getCompiled` function needs
- then just call `getCached` from both instead
- `getDiagnostics` and `getCompiled` were near identical except for the cache they used and `checkImports`, which are both parameters now
- `getCompiled` also had a logging statement (called in both `noCache` and w/ cache branches), which was moved to before the call to `getCompiled` instead
- the `type` param was composed into another function in `getDiagnostics` before the call too `getCached` now
- this simplifies all the cache code to one …

refactor(cache): split a `getCached` function out

---

.github/pull_request_template.md

Add a brief PR template for contributors to write against
- Follow-up to "Next Steps" from #350
- See GitHub's docs on PR templates [here](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)
- keeping it short and simple for now, but this is basically the format that the majority of my PRs follow
- can add more sections or optional sections as needed in the future
- (e.g. I've used "References", "Next Steps", etc in this codebase)
- this should help keep PRs consistent, which makes them easier to read and review
- (similar rationale as that for code style consistency)
- should also help preserve the historical context and rationale behind PRs
- which also makes reviews _significantly_ …

github: add a Pull Request template

---

__tests__/rollingcache.spec.ts
src/rollingcache.ts
src/tscache.ts

The `checkNewCache` parameter in `RollingCache` is always set to `true`, so remove it to simplify the code
- it is set to `true` in every usage, so just always check the new cache and remove the parameter entirely
- rewrite the comments to reflect this change
- and condense them a bit
- modify tests a bit to reflect this change as well

clean(cache): remove unused `checkNewCache` parameter

---

src/tscache.ts

The `codeCache` should be invalidated when imports change if declarations are needed, because imports' types can change the resulting declaration. 
- Fixes #292
**EDIT**: also added `!isolatedModules` to the check, see below comments regarding, e.g. enums, that could cause compiled JS code to change as well when imports change
- previously, the `checkImports` flag was set to `true` for type-checking, but `false` for compilation
- I _believe_ it is `false` because the compiled JS shouldn't change if an import changes
- though I'm not sure if that was the original intent behind the code
- problematically though, compilation results can include declarations, and those _can_ change if imports change
- for instance, the types of an import can change the declaration that is output
- so now, …

fix(cache): invalidate `codeCache` in most cases when imports change

---

src/index.ts
src/parse-tsconfig.ts
src/print-diagnostics.ts

Changes the default configuration of `pretty`, so now pretty-printing is the default, as it is for `tsc` and in the TSConfig Reference.
- per https://www.typescriptlang.org/tsconfig#pretty
- TS 2.9 [changed the default](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-9.html#--pretty-output-by-default) to `true`
- so this is a legacy remnant of older versions of TS
- this is why `tsc` by default pretty prints, even when `pretty` is unset
- only if it is _explicitly_ set to `false` does it not do that
- so change rpt2's diagnostic printing to be `pretty` by default as well
- I think this is a pretty _big_ DX improvement, to be honest
- I always thought something was up with the error reporting, but saw that there was code for `pretty`, so didn't quite connect the …

fix(diagnostics): `pretty` defaults to `true` in TS 2.9+

---

src/index.ts

Adds a workaround for a Rollup bug that causes duplicate error messages
- Fixes #103
- Goes along with #372, which makes this bug much more noticeable
- per https://github.com/ezolenko/rollup-plugin-typescript2/issues/103#issuecomment-1172820658 and my investigation in #372, it seems like Rollup has a bug where it duplicates some error message
- this occurs when the error has a stack (or frame) which contains the error message itself
- Rollup prints _both_ the error message _and_ the stack in that case, causing duplication
- this fix adds a workaround for this upstream Rollup bug
- it detects if there is a stack and if the message is duplicated in the stack
- if so, it removes the duplication in the stack
- this workaround should be forward-compatible if this behavior is fixed upstream
- …

fix(diagnostics): workaround Rollup duplicating error messages

---

README.md

Improve grammar and formatting in the README, as well as add several [TSConfig Reference](https://www.typescriptlang.org/tsconfig) links.
- improve grammar in several places
- mostly add "the" and commas in several places where they were missing
- and put a period or semicolon in a few places where there was a comma splice
- for "deep merge", parens were used, whereas a colon is a better fit
- consistently use "(see #x)", instead of sometimes using parens and other times using commas
- also change "only if `useTsconfigDeclarationDir`" to "unless `useTsconfigDeclarationDir`" for clarity
- have looked at this many times and thought something was unintuitive about this: `useTsconfigDeclarationDir` defaults to `false` after all
- "typescript" -> "TypeScript" as a proper noun
- "js" -> "JS" …

docs: improve grammar & formatting, plus add TSConfig Reference links

---

__tests__/rollupcontext.spec.ts
src/index.ts
src/rollupcontext.ts

Clean up some old backward-compat checks that are no longer necessary for the minimum version of Rollup that rpt2 requires
- Follow-up to https://github.com/ezolenko/rollup-plugin-typescript2/pull/345#issuecomment-1170542354, where I realized several of these checks were legacy and no longer needed
- we require Rollup `>=1.26.3` in the peerDeps and the README and have for years now
- (and Rollup is currently at `2.75.7`, so this is a pretty low target)
- as such, we can remove various checks that are legacy backward-compat remnants for old Rollup versions:
- `this.meta` was added to `options` in `1.1.0`: https://github.com/rollup/rollup/blob/master/CHANGELOG.md#110
- `this.addWatchFile` was added at least in `1.0.0`: https://github.com/rollup/rollup/blob/master/CHANGELOG.md#100
- …

clean: remove backward-compat checks for old Rollup versions

---

README.md
__tests__/check-tsconfig.spec.ts
src/check-tsconfig.ts

Update docs and `check-tsconfig` error message to mention `module: "ES2020"` compatibility
- it's already been supported since eb1dd17babde0b22e9540b12e671eb56d9d6bce0, but the docs and error message were not updated to mention it
- so add both to make sure users aren't confused
- also re-order it to be ES2015, ES2020, then ESNext consistently, which is their module order (c.f. https://github.com/microsoft/TypeScript/issues/24082)
- modify test to account for the new error message
- make it a bit more resilient to change by only testing a substring as well (c.f. https://jestjs.io/docs/expect#tothrowerror)

docs: mention `module: "ES2020"` compatibility

---

__tests__/integration/errors.spec.ts

The integration tests (#371) and `pretty` default change (#372) got merged simultaneously, so the tests need to be updated to handle the new `pretty` default
- `master` is currently [failing CI](https://github.com/ezolenko/rollup-plugin-typescript2/runs/7208202793?check_suite_focus=true) due to this
- the coloration of the errors is quite different when using `pretty`
- so instead of re-implementing TS's colors in the tests, just test a portion that is the same color: the error text
- also TS doesn't specify semantic vs. syntax, that's something `print-diagnostics` does
- this test is more resilient to change as well I suppose since no error codes or colors
Add unit tests for both `pretty` and non-`pretty` versions of errors; currently `print-diagnostics` is one of the few files without …

fix(test): handle `pretty` formatting

---

README.md

Add a permalink back to the specific previous version of `rollup-plugin-typescript` that `alexlur`'s fork likely started from
- Closes #307 by incorporating https://github.com/ezolenko/rollup-plugin-typescript2/pull/307#discussion_r895089906
- as the `alexlur` fork no longer exists / 404s, permalink back to og rpt (rpt1)
- which is archived and still exists under the `rollup` org
- as requested in issues

docs: add a permalink to the og rpt

---

README.md

`check: false` is sometimes known as `transpileOnly` in other TS integrations
- Fixes #302 
- this is a common name in other TS integrations and has been mentioned in the issues before
- so add it in the docs for searchability

docs: mention `transpileOnly` in `check: false`

---

src/index.ts

Make `noErrors = false` unconditional again in `emitSkipped`
- Follow-up to https://github.com/ezolenko/rollup-plugin-typescript2/pull/344#discussion_r914336553
- apparently `emitSkipped` can indeed happen without there being a semantic or syntactic error
- so add back the previous unconditional behavior of `noErrors`
- still not clear what exactly triggers `emitSkipped` though, see my TS issue https://github.com/microsoft/TypeScript/issues/49790

fix: add back `noErrors = false` to `emitSkipped`

---

__tests__/integration/errors.spec.ts
src/parse-tsconfig.ts

Improve the error message when a `tsconfig` path doesn't have a file. The error message should say the path passed in, not `'undefined'`
- Fixes a bug I found while writing integration tests in #371 
- per the conditional above this line, `file` is falsey, so printing it doesn't make sense
- per same conditional though, `pluginOptions.tsconfig` exists, so we can print that
- fixes a test `TODO`/`FIXME` that had to workaround this bug as well

fix: missing `tsconfig` error shouldn't say `undefined`

---

src/check-tsconfig.ts
src/tslib.ts

Add `rpt2: ` prefix to remaining, unprefixed error messages
- Fixes #300
- most were added in ff8895103c8466694e7d8eeb734f51d2850670d8, but these two were missed
- this should now cover all **thrown** errors
- they only get thrown in the [`options`](https://rollupjs.org/guide/en/#options) hook, which does not implement Rollup's `this.error`
- all other errors are already auto-prefixed by RollupContext etc

feat: add rpt2 prefix to remaining errors

---

src/index.ts

Capture `this.meta.watchMode` when it is available
- `process.env.ROLLUP_WATCH` is only set when using the CLI
- when using watch mode through [the Rollup API](https://rollupjs.org/guide/en/#rollupwatch), this is not set
- but since Rollup [2.14.0](https://github.com/rollup/rollup/blob/master/CHANGELOG.md#2140), `this.meta.watchMode` is available
- still check the env variable for backward-compat on older Rollup versions
- notably, this is needed to test watch mode, since the tests are done via the Rollup API

feat: capture watch mode when called via the Rollup API

---

__tests__/integration/errors.spec.ts
__tests__/integration/fixtures/errors/import-type-error.ts
__tests__/integration/fixtures/errors/type-only-import-with-error.ts
src/index.ts

Type-check some type-only files that were missed in the `transform` hook but are in `parsedConfig.fileNames`
- Fixes #298 (which uses `include` globs)
- Fixes the latter half of #254 (which uses `include` globs)
- Partial workaround for #7, but not complete (see details below)
- Similarly partially fixes some things mentioned in #211, but does not _truly_/completely fix it as it uses `files` (see details below)
- See my root cause analysis in https://github.com/ezolenko/rollup-plugin-typescript2/issues/298#issuecomment-1146658442 for how I plan to fix that
- Partially fixes the most common issue that I mentioned in https://github.com/ezolenko/rollup-plugin-typescript2/pull/311#issuecomment-1115491161, type-only imports
- type-only files never get processed by Rollup as their imports are …

fix: type-check `include`d files missed by `transform` (type-only files)

---

__tests__/integration/errors.spec.ts
src/index.ts

Ensure that the type-only / "missed" type-check doesn't duplicate on Windows
- Fixes https://github.com/ezolenko/rollup-plugin-typescript2/pull/345#issuecomment-1182156954 and the currently [failing CI on `master`](https://github.com/ezolenko/rollup-plugin-typescript2/runs/7305629642?check_suite_focus=true)
- gotta remember to normalize file names 🙃
- this fixes a failing test on Windows by fixing the underlying bug
- refactor: improve normalization in `errors.spec`
- normalize _all_ calls to `local`, instead of just one
- this doesn't affect the tests, only the source code change does, but I added this first and it's better practice / test future-proofing
I confirmed [on CI on my fork](https://github.com/agilgur5/rollup-plugin-typescript2/actions/runs/2666782630) that tests pass on …

fix: don't duplicate type-only check on Windows

---

README.md

Minor docs clarifications, fixes, and style consistency
- Follow-up to #375
- the docs for `clean` don't seem to have been updated after f15cb84dcc99a0bd20f3afce101c0991683010b6 (#68), which slightly changed how it works
- also clarify that "wipes out cache" means it deletes _all_ previous caches by saying "wipes any existing cache" instead
- fix the `include` default explanation to mention `.tsx` files as well, since the regex includes those
- also add code backticks and capitalize TypeScript etc (guess I missed this option in my previous docs PRs? or I intentionally left it as a separate change a while ago...)
- also add code backticks around `node_modules` in `cacheRoot` as well while at it
- use non-rendered newlines between sentences for markdown style consistency

docs: clarify `clean: true` and default `include`

---

src/tscache.ts

Add quotes around vars in error messages in the cache's `clean` method
- Follow-up to #358
- Note that the error messages beforehand _also_ weren't quoted
- follows the style of most of the other errors in the codebase
- when referencing a variable, file path, etc, put quotes around it in the output
- so it's easier to distinguish in the log

dx(cache): improve `clean` edge-case errors with quotes

---

src/index.ts

Provide a bit more details when erroring on `emitSkipped` and link to my TS issue since this is unfortunately undocumented
- See my upstream issue: https://github.com/microsoft/TypeScript/issues/49790
- Related to #254, #264, https://github.com/ezolenko/rollup-plugin-typescript2/pull/371#issuecomment-1174339120
- a few issues have reported that "failed to transpile" is a vague / confusing error
- and `emitSkipped` actually _doesn't_ mean that it failed to transpile, as, in current versions of TS, it's not due to syntactic or semantic errors (c.f. https://github.com/microsoft/TypeScript/issues/2290#issuecomment-78203910, which is linked in my upstream issue)
- so explicitly say "Emit skipped" instead, which is slightly less vague, in that it can actually be used as a search term
- and …

dx: be more explicit with `emitSkipped` error

---

src/index.ts

Keep the `DocumentRegistry` b/t watch cycles instead of resetting it
- Follow-up to my findings in #386, `3.` specifically
- Potential fix for the OOM in #177, but difficult to tell since there's no repro and it's coming from TS itself
- we can re-use the same one during watch instead of resetting it in the `options` hook
- should make the LS a bit faster / more efficient in watch mode as most source files are shared between watch cycles
1. `DocumentRegistry` can actually be shared between multiple LSes for #177. Per the [TS LS Wiki](https://github.com/microsoft/TypeScript/wiki/Using-the-Language-Service-API#document-registry), sharing `DocumentRegistry` is actually recommended, as, minimally, `lib.d.ts` could be shared between projects.
- But to do that we'd probably have to expose an …

optim(watch): don't reset `DocumentRegistry` b/t watch cycles

---

src/tscache.ts

Syntactic diagnostics are only per-file, so we don't need to `checkImports` in the cache's `isDirty` check for them
- Per the [TS LS Wiki](https://github.com/microsoft/TypeScript/wiki/Using-the-Language-Service-API#design-goals), syntactic diagnostics only need to parse the specific file in question
- since syntax is independent of imports; imports only affect semantics
- Just happened to finally realize this while reading the LS Wiki for #388 .
- Related to #369 ; that was a de-opt for `codeCache`, this is an optimization for `syntacticDiagnosticsCache`

optim(cache): don't check imports for syntactic diagnostics

---

src/index.ts

Put `generateRound = 0` in `buildEnd` instead of `transform`
- Follow-up to the `buildEnd` refactor in #345
- since the `buildEnd` hook exists nowadays, we can just reset `generateRound` there, right before `generateBundle` is called for each output and increments it per output
- also modify the comment to account for this change and the fact that `buildEnd` exists and is used nowadays
Note that `generateRound` is literally only used for logging purposes now, since the `buildEnd` refactor made it otherwise unneeded for its original purpose of not duplicating type-check errors between different outputs.
Could totally remove it as well 🤷

refactor: move `generateRound = 0` to `buildEnd`

---

src/index.ts

Move the repeated `if (snapshot)` check into `typecheckFile`
- Follow-up to #344
- just slightly simplify / DRY up repeated code
- this matches the style of some of the other functions in the codebase, such as [`emitDeclaration`](https://github.com/ezolenko/rollup-plugin-typescript2/blob/e5e3ccd7938e8f24ac959dde5dfe73848890bdfa/src/index.ts#L339), [`getAllReferences`](https://github.com/ezolenko/rollup-plugin-typescript2/blob/e5e3ccd7938e8f24ac959dde5dfe73848890bdfa/src/tscache.ts#L65), etc
- also fix indentation in `typecheckFile`
- apparently I double-intended this accidentally, so make it single indent

refactor: move `snapshot` check into `typecheckFile`

---

src/index.ts

Split out a common `addDeclaration` func matching `typecheckFile`
- Similar to #344 but for declarations instead of type-checking
- DRY it up and follow the same pattern as `typecheckFile`
- this also standardizes some things like normalization etc so that they're harder to miss

refactor: split out an `addDeclaration` func

---

src/tscache.ts

Condense `walkTree` further to just 4 LoC
- Follow-up to #359 I guess
- `forEach` returns `void`, so we can just `return` it and condense the `if` a bit

refactor(cache): further condense `walkTree`

---

src/print-diagnostics.ts

Simplify some conditionals in `print-diagnostics` by reducing nesting
- Follow-up / related to https://github.com/ezolenko/rollup-plugin-typescript2/pull/335#issuecomment-1151365993
- reduce the complexity of the code by decreasing the amount of nesting
- note that `print` returns `void` anyway, so calling it within the `return` statement doesn't change anything
- and this is within a `void` `forEach` at that too

refactor(diagnostics): simplify some conditionals

---

src/index.ts

This reverts commit e145d0baebbbef1eec691b99d1ce0dce1e49f38c / PR #336
**NOTE**: this may be considered breaking, so we may want to release this in a breaking release as such. I've left this PR as draft as such. That being said, this could also be considered as just a bugfix as the original PR was made in error and caused a bug.
Revert back to using `.vue.d.ts` for Vue declarations
- Per follow-up discussion on [the original issue](https://github.com/ezolenko/rollup-plugin-typescript2/issues/224#issuecomment-1193350666) and [to-be-reverted PR](https://github.com/ezolenko/rollup-plugin-typescript2/pull/336#issuecomment-1179476746), it seems that the request to use `.d.ts` instead of `.vue.d.ts` was made in error
- `.d.ts` seems to only be necessary if Vue users were importing `.vue` SFCs …

revert: back to using `vue.d.ts` instead of `.d.ts` for Vue declarations

---

__tests__/integration/errors.spec.ts
__tests__/integration/fixtures/no-errors/index.ts
__tests__/integration/helpers.ts
__tests__/integration/no-errors.spec.ts
__tests__/integration/watch.spec.ts

Creates a test harness/structure for [watch mode](https://rollupjs.org/guide/en/#rollupwatch) tests and adds an initial test suite to it
- Built on top of #371 and #384
- Follow-up to https://github.com/ezolenko/rollup-plugin-typescript2/pull/371#issuecomment-1174339120
- test starting watch mode, changing a file, and adding a semantic error
- put this in a separate file as it has its own complexity to deal with (see below)
- initially put it inside `no-errors`, but it got pretty confusing; this structure is a good bit simpler
- refactored this a couple times actually
- add two watch mode helpers
- `watchBundle` is very similar to `genBundle` but with some watch mode nuances (like returning a watcher)
- `watchEnd` is a bit complicated async wrapper around a listener interface to make …

test: add initial watch mode test suite

---

__tests__/check-tsconfig.spec.ts

Be more precise with the checks in `check-tsconfig.spec.ts` and reorder things a bit
- `check-tsconfig.spec.ts` should now match the structure of `parse-tsconfig.spec.ts` from #397
- Follow-up to #321 
- `toBeFalsy()` was a bit imprecise and always felt as such, especially since `checkTsConfig` returns `void`
- so instead check that it doesn't throw, which matches the test _intent_
- reorder the tests a bit to match existing test style: non-errors first, then errors
- and separating into two different test blocks parallelizes them as well
- also add an ES2020 check as well
- follow-up to eb1dd17babde0b22e9540b12e671eb56d9d6bce0 and #376

refactor(test): use more specific checks in `check-tsconfig` spec

---

__tests__/tslib.spec.ts

Get to 100% coverage of `tslib.ts` by adding a check for error case
- Follow-up to #321
- use Jest's [module mocks](https://jestjs.io/docs/jest-object#jestmockmodulename-factory-options) to test the error case of `tslib.ts` when `tslib` fails to import
- this took a bit of work to figure out bc, per the in-line comments, the ordering and module subpath were both _required_
- it was pretty confusing for a while until I realized what might be going wrong

test: 100% coverage for `tslib.ts` (error case)

---

src/index.ts

Removes the `if (generateRound === 0)` check in the `options` hook as it is redundant / unnecessary
- Related to, but independent of, #390
- when `options` is called, `generateRound` should have already been reset to `0`, so this is redundant / unnecessary
- `options` is only called once per watch cycle
- `options` is also an `input` hook, not an `output` hook, i.e. it's only called once for _all_ outputs, _not_ per each output
- `generateRound` only tracks the output round
- this might be leftover historical remnants prior to Rollup officially separating `output` hooks, but even before then, it should only have been called once for _all_ outputs
- since, per the Rollup API, it's only called during `rollup.rollup` and not during `bundle.generate` etc
- c.f. old docs …

clean: remove redundant `generateRound === 0` check

---

src/tscache.ts

Add an `istanbul-ignore` statement to the `else` check in the cache regarding corrupted or otherwise "broken" cache
- Related to https://github.com/ezolenko/rollup-plugin-typescript2/pull/358#issuecomment-1159295541
- similar to the other safety checks in `clean`, this won't be hit during normal usage

test(cache): ignore coverage for corrupted cache check

---

__tests__/integration/no-errors.spec.ts

~**NOTE**: this is built on top of #386 as the `testDir` changes there are required to have a correct `outDir`. As such, I've marked this PR as "Draft" until that PR is merged.~
Rebased on top and marked as ready for review.
Add a test for `declarationMap` `sources` to make sure they're correct after #221 / #204
- Follow-up to https://github.com/ezolenko/rollup-plugin-typescript2/pull/371#issuecomment-1174339120
- since we set a placeholder `outDir` initially, TS sets declaration map sources to that placeholder dir
- then, after #221, we remap that to the correct dir that Rollup outputs to
- this test checks that the remap happens and is correct

test: ensure `declarationMap` sources are correct 

---

src/index.ts

Just removes an unnecessary quote
- noticed it in #411's logging
- follow-up to #366
- must've been a copy+paste mistake or something

fix(dx): remove extra quote in `emitDeclarationOnly` log statement

---

__tests__/context.spec.ts
__tests__/fixtures/context.ts
__tests__/get-options-overrides.spec.ts
__tests__/parse-tsconfig.spec.ts

~**NOTE**: this is built on top of #397 as that also uses the `context` helper. It may also merge conflict with #396 if that is merged. As such, I've marked this PR as "Draft" until those PRs are merged (or otherwise closed).~
Rebased on top, fixed merge conflicts, and marked as ready for review.
Significantly simplify the `context` helper used in the unit tests with more forceful type-casting and directly using Jest mocks. This makes all usage of `context` significantly easier and less hacky, as can be seen in the changed tests here.
- Follow-up to #321 / #135
- since we're type-casting it anyway, we can heavily simplify this and remove the stubs entirely
- they're actually unused in the unit tests, so we don't need them at all
- besides the type-checking, which we force with a cast …

refactor(test): heavily simplify the `context` helper 

---

CONTRIBUTING.md
__tests__/print-diagnostics.spec.ts

~**NOTE**: this is built on top of #404 as it uses the `context` changes made there. #404 is itself built on top of #397. As such, I've marked this PR as "Draft" until those PRs are merged.~
Rebased on top and marked as ready for review.
Adds unit tests for all scenarios of `print-diagnostics.ts`
- Follow-up to #321
- test all the different categories and formattings
- full unit test coverage now! (except for `index`/`tscache`, which integration tests cover)
- (since this is in "Draft" status right now, full coverage does also depend on #397 being merged)

test: add `print-diagnostics` spec 

---

__tests__/context.spec.ts
__tests__/fixtures/context.ts
__tests__/parse-tsconfig.spec.ts
src/context.ts
src/get-options-overrides.ts
src/index.ts
src/parse-tsconfig.ts
src/print-diagnostics.ts
src/tscache.ts

Remove `ConsoleContext` (and the need for it) by using the [`buildStart`](https://rollupjs.org/guide/en/#buildstart) hook instead of the [`options`](https://rollupjs.org/guide/en/#options) hook
- Follow-up to https://github.com/ezolenko/rollup-plugin-typescript2/pull/345#issuecomment-1200277838
- the only reason that `ConsoleContext` was still used was because the `options` hook doesn't support certain context functions like `this.error` / `this.warn` etc
- but `buildStart` does! so we can just move pretty much everything into `buildStart` instead
- didn't move setting `rollupOptions` because that value gets hashed and the value in `buildStart` is different, as it is after all plugins' `options` hooks have ran
- I'm not sure which is the better one to hash, but I left it as is so that the …

clean: remove `ConsoleContext` entirely by using `buildStart`

---

src/index.ts

~**NOTE**: this is built on top of #414 as it uses the `buildStart` changes made there. As such, I've marked this PR as "Draft" until #414 is merged.~
Rebased on top and marked as ready for review.
Use the `buildStart` hook added in #414 to simplify `cache()` to `cache`
- as everything is created in the `buildStart` hook now (which has `RollupContext`), we can create the `cache` there too
- no need for slightly hacky, lazy creation during `transform` anymore
- simplifies it and also standardizes it so it's created the same way as all the other instance vars
- fix: reset `cache` after each watch cycle
- previously the cache was never reset, meaning that if anything became dirty in a watch cycle, it would never get reset back
- I noticed this in the processing of writing watch mode tests in …

refactor(cache): simplify creating / using the `cache` var

---

__tests__/integration/errors.spec.ts
__tests__/integration/fixtures/no-errors.ts
__tests__/integration/fixtures/no-errors/index.ts
__tests__/integration/fixtures/no-errors/type-only-import-import.ts
__tests__/integration/fixtures/no-errors/type-only-import.ts
__tests__/integration/helpers.ts
__tests__/integration/no-errors.spec.ts
__tests__/integration/watch.spec.ts
src/index.ts

~**NOTE**: this is built on top of #403 as it changes its code a bit. #403 is itself built on top of #386. As such, I've marked this PR as "Draft" until those PRs are merged.~
Rebased on top and marked as ready for review. (surprisingly clean rebase)
Also this might be the first time this repo has more open PRs than open issues 😮 
Completely handle the long-standing issue of type-only imports
- Uses the solution I proposed in my root cause analysis in https://github.com/ezolenko/rollup-plugin-typescript2/issues/298#issuecomment-1146658442
- Fixes #7 as all type-only imports go through the `resolveId` hook now, which adds them to the cache (calls `cache().setDependency`)
- Fixes #211
- And its various duplicates: fixes #24, fixes #106, fixes #409
- Fully fixes the most common issue that I …

fix: handle all type-only imports by piping TS imports

---

CHANGELOG.md

Add a `CHANGELOG.md` that references the release notes on [GH Releases](https://github.com/ezolenko/rollup-plugin-typescript2/releases)
- Resolves #418
- we have release notes already in GH releases, so add a simple `CHANGELOG.md` that references it
- I use something [similar](https://github.com/agilgur5/react-signature-canvas/blob/64c7c4989cb6dceb8ac92e03d43070b8ff5d1043/CHANGELOG.md) in most of my libraries
- this should hopefully make it easier for users to find the release notes in case they hadn't seen them on GH before

docs: add a simple `CHANGELOG.md` that references GH releases

---

CONTRIBUTING.md
__tests__/diagnostics.spec.ts
src/diagnostics.ts
src/index.ts
src/parse-tsconfig.ts
src/tscache.ts

- Move `diagnostics` funcs into a single file named `diagnostics.ts`
- Follow-up to #396 (and #413)
- This should be the last of such "consolidation" PRs, as these 3 files were the only ones where I thought the separation was more confusing than helpful, and where consolidation simplified things, IMO
- Add a unit test for `convertDiagnostic`
- Tiny bugfix `\n` -> `formatHost.getNewLine()`
- This doesn't seem to have ever affected anyone; I'm guessing either Node or people's terminals auto-translated the newlines b/t OSes or something? So this is more of a semantic bugfix in that sense
refactor:
- move `IDiagnostic` and `convertDiagnostic` from `tscache` to `print-diagnostics`, then rename it to `diagnostics.ts`
- the diagnostic funcs being in `tscache` always felt like a strange place for …

refactor: consolidate `diagnostics` funcs into single file 

---

__tests__/integration/errors.spec.ts
src/index.ts

If an error occurs during the `buildStart` hook, make sure that the `buildEnd` hook doesn't hide the error with its own error
- in this case the `buildDone` func had an uninitialized `cache` var, as it's initialized _in `buildStart` after_ this thrown error
- Fixes #421 
- See root cause analysis in https://github.com/ezolenko/rollup-plugin-typescript2/issues/421#issuecomment-1247116271
- Caused by #414 + #415
- per in-line comment, if an error occurs during `buildStart` initialization, then the `cache` may not exist yet during `buildDone`
- since we now use `context.error` instead of `throw` during initialization (from the `options` -> `buildStart` change), `buildEnd` will run during initialization - and the `cache` var is initialized in `buildStart` as well, so if an error occurs before …

fix: don't error out while catching a `buildStart` error

---

__tests__/integration/no-errors.spec.ts

Increase the timeout on the `no-errors` integration test suite
- Follow-up to #371, where, per the commits, I bumped it several times due to CI timeouts
- this was still occasionally failing on CI at 15s, so bump up a bit
- c.f. [this run](https://github.com/ezolenko/rollup-plugin-typescript2/actions/runs/3075482590/jobs/4968935300), [this run](https://github.com/ezolenko/rollup-plugin-typescript2/actions/runs/3038898669/jobs/4893183507), [this run](https://github.com/ezolenko/rollup-plugin-typescript2/actions/runs/3038898669/jobs/4893561438), and many more
- only `no-errors` was timing out, which makes sense, since it does 3 builds for the first test to test against the cache
- this potentially could be optimized, but it started getting complicated to do so (including some concurrency …

test: increase `no-errors` integration timeout to 20s

---

src/index.ts
src/tscache.ts

Fixes #443, should incidentally fix #444
Disabling cache in watch mode, speeds it up considerably, which was the whole point of having a cache in the first place.
This is slightly different from simply using `clean: true` for watch mode -- `clean: true` also deletes all old caches. `clean: false` in watch mode would bypass cache without touching old caches.

disabling cache in watch mode

---

src/index.ts

Follow-up to https://github.com/ezolenko/rollup-plugin-typescript2/pull/451#discussion_r1256333929, ensure declarations are _always_ ignored during resolution.
- Technically, this fixes a tiny new regression whereby a user could have accidentally (or incorrectly) made rpt2 try to process a directly imported declaration
- rpt2 should _always_ ignore declarations
- regardless of the `exclude`; as in, if a user accidentally removes declarations in an override, rpt2 should still not directly read declarations
- as they are normally read ambiently by TS and not _directly_ by Rollup or TS
- this also ensures that the `resolveId` check is the same as the type-only resolve pre-check
- adds a comment referencing why this is done. see my commit message step-by-step details on that one, it's a bit …

fix: hardcode declaration extension check
